export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REQUEST_ITEM = 'CART_REQUEST_ITEM';
export const CART_FAIL_ITEM = 'CART_FAIL_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
